[build]
  command = "npm run build"
  publish = "dist/CountryPedia"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_FLAGS = "--legacy-peer-deps"

